In [1]:
import pandas as pd
import numpy as np 
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.concatenate([arr1, arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [7]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
ser1 = Series([0,1,2], index=['t','u','v'])

In [11]:
ser2= Series([3,4], index=['x','y'])

In [12]:
pd.concat([ser1,ser2])

t    0
u    1
v    2
x    3
y    4
dtype: int64

In [13]:
pd.concat([ser1,ser2], axis=1)

D:\Users\joshi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.


0    1
t  0.0  NaN
u  1.0  NaN
v  2.0  NaN
x  NaN  3.0
y  NaN  4.0

In [15]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['x','y','z'])

dframe2 = DataFrame(np.random.randn(3,3), columns=['y','q','x'])

dframe1


x         y         z
0 -0.454757  0.046169 -1.028139
1 -0.575972  0.110180  0.261852
2  0.639041 -0.036961  0.321510
3  0.112359 -2.297877 -0.737346

In [16]:
dframe2

y         q         x
0  0.194248 -0.143286 -0.549691
1  0.494575  1.961335 -0.777819
2  0.817363 -0.828442 -0.160023

In [21]:
pd.concat([dframe1,dframe2], ignore_index=True)

D:\Users\joshi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.


q         x         y         z
0       NaN -0.454757  0.046169 -1.028139
1       NaN -0.575972  0.110180  0.261852
2       NaN  0.639041 -0.036961  0.321510
3       NaN  0.112359 -2.297877 -0.737346
4 -0.143286 -0.549691  0.194248       NaN
5  1.961335 -0.777819  0.494575       NaN
6 -0.828442 -0.160023  0.817363       NaN

In [23]:
series1 = Series([2,np.nan, 4,np.nan,6,np.nan], index=['q','r','s','t','u','v'])

In [24]:
series1

q    2.0
r    NaN
s    4.0
t    NaN
u    6.0
v    NaN
dtype: float64

In [25]:
series2= Series(np.arange(len(series1)), dtype=np.float64, index=['q','r','s','t','u','v'])

In [26]:
series2


q    0.0
r    1.0
s    2.0
t    3.0
u    4.0
v    5.0
dtype: float64

In [27]:
Series(np.where(pd.isnull(series1), series2, series1), index=series1.index)

q    2.0
r    1.0
s    4.0
t    3.0
u    6.0
v    5.0
dtype: float64

In [29]:
series1.combine_first(series2)

q    2.0
r    1.0
s    4.0
t    3.0
u    6.0
v    5.0
dtype: float64